"""Add FormSubmission table

Revision ID: 6df106850af3
Revises: 546f84e030c3
Create Date: 2026-01-06 20:27:25.490679

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "6df106850af3"
down_revision: str | None = "546f84e030c3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
